const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Timer,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnJump
	];
};
self.C3_JsPropNameTable = [
	{BackgroundTile: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{SolidTile: 0},
	{Sine: 0},
	{Rotate: 0},
	{Timer: 0},
	{MovingSolidTile: 0},
	{Jumpthru: 0},
	{JumpThruTile: 0},
	{Keyboard: 0},
	{Text: 0},
	{Door: 0},
	{Medusa: 0},
	{Medusa2: 0},
	{Mario: 0},
	{Wrap: 0},
	{Bullet: 0},
	{Flying: 0},
	{lava: 0},
	{Key: 0},
	{Sprite: 0},
	{Audio: 0},
	{Screenshot20260427At23946PM: 0},
	{Screenshot20260427At24412PM: 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{Text2: 0},
	{TiledBackground3: 0},
	{"3DCamera": 0},
	{Sprite3: 0},
	{TiledBackground6: 0},
	{Keycount: 0}
];

self.InstanceType = {
	BackgroundTile: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	SolidTile: class extends self.ITiledBackgroundInstance {},
	MovingSolidTile: class extends self.ITiledBackgroundInstance {},
	JumpThruTile: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Door: class extends self.ISpriteInstance {},
	Medusa: class extends self.ISpriteInstance {},
	Medusa2: class extends self.ISpriteInstance {},
	Mario: class extends self.ISpriteInstance {},
	Flying: class extends self.ISpriteInstance {},
	lava: class extends self.ITiledBackgroundInstance {},
	Key: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Screenshot20260427At23946PM: class extends self.ISpriteInstance {},
	Screenshot20260427At24412PM: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {}
}